#source 'http://rubygems.nos.ncu.edu.tw'
source 'https://rubygems.org'
gem 'json'
gem 'rack'
gem 'rack-cors'
gem 'rack-contrib'
gem 'grape'
gem 'grape-swagger', :git => 'https://github.com/ruby-grape/grape-swagger.git'
gem 'grape-entity'
gem 'grape_logging', :git => 'https://github.com/aserafin/grape_logging.git'
gem 'rest-client'
gem 'rake'
